"""The share-bundle core (SPEC.md 50.2, v0.36) — the 47.4 content
contract as pure functions.

`cli._cmd_share` (47.4) and the app's "Build share bundle" panel
(50.2.3) both build their bundles from these three, so the contract has
one home: the caller injects the regenerated `report.html` (47.4.2),
and the zip bytes are deterministic (47.4.3, G2).

House rules: stdlib only (3); import-cycle-free (this module never
imports `cli`); streamlit-free (23.1).
"""
from __future__ import annotations

import io
import zipfile
from pathlib import Path

# SPEC.md 47.4.3: the fixed `ZipInfo` timestamp — two shares of the same
# run dir are byte-identical.
_ZIP_DATE = (1980, 1, 1, 0, 0, 0)


def share_payload(run_dir, report_html: str | None = None) -> dict[str, bytes]:
    """SPEC.md 50.2.1 (v0.36): the 47.4.2 content contract as a
    name-sorted dict of bytes — the caller-injected `report_html`
    (47.4.2: always regenerated by the caller, never read from the run
    dir), `summary.json` (required), `run_config.json` (37.1) and
    `best_spec.json` when present, and every flat `*.svg` (nested dirs
    excluded, 47.4.2). A missing `summary.json` is a `ValueError`
    (47.4.4) — the caller surfaces it (CLI: rc 1 + stderr; app: a local
    error)."""
    run_dir = Path(run_dir)
    if not (run_dir / "summary.json").is_file():
        raise ValueError(
            f"no summary.json in run dir {str(run_dir)!r} "
            f"(SPEC.md 47.4.4)")
    payload: dict[str, bytes] = {}
    if report_html is not None:  # 47.4.2: always regenerated by the caller
        payload["report.html"] = report_html.encode("utf-8")
    for name in ("summary.json", "run_config.json", "best_spec.json"):
        p = run_dir / name
        if p.is_file():
            payload[name] = p.read_bytes()
    for p in sorted(run_dir.glob("*.svg")):  # flat SVGs only (47.4.2)
        payload[p.name] = p.read_bytes()
    return dict(sorted(payload.items()))  # 47.4.3: sorted entry order


def zip_bundle_bytes(payload: dict[str, bytes]) -> bytes:
    """SPEC.md 50.2.1 (v0.36): the deterministic in-memory zip (47.4.3:
    fixed 1980-01-01 `ZipInfo`, `ZIP_DEFLATED`, entries in sorted name
    order) — the CLI `share` (47.4.3) and the app download (50.2.3)
    produce byte-identical bundles for the same payload (G2)."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name in sorted(payload):  # 47.4.3: sorted entry order
            info = zipfile.ZipInfo(name, date_time=_ZIP_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, payload[name])
    return buf.getvalue()


def write_share_zip(payload: dict[str, bytes], out) -> Path:
    """SPEC.md 50.2.1 (v0.36): the same deterministic bytes (47.4.3)
    written to a file (parent dirs created); returns the output path.
    `out.read_bytes() == zip_bundle_bytes(payload)` always."""
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(zip_bundle_bytes(payload))
    return out
